/**
 * Business logic layer (skeleton)
 *
 * TODO: Fill in these functions with the logic described in the spec:
 * - uniqueness of autogenerated shortcodes
 * - handling custom shortcode collisions
 * - expiry handling
 * - recording click events (timestamp, referrer, coarse geo)
 *
 * NOTE: This file intentionally contains placeholders to keep the exam work yours.
 */

const storeModel = require('../models/store');
const timeUtils = require('../utils/time');
const shortcodeUtils = require('../utils/shortcode');
const config = require('../config/config');

/**
 * createShortUrl({ url, validityMinutes, desiredShortcode })
 * - Validate uniqueness, create object, persist in storeModel
 * - Return { shortLink, expiry }
 */
async function createShortUrl({ url, validityMinutes, desiredShortcode }) {
  // TODO: implement
  // Steps:
  // 1. If desiredShortcode provided: check format & uniqueness -> if taken return conflict
  // 2. If not provided: generate unique shortcode (use shortcodeUtils.generateUniqueShortcode(storeModel))
  // 3. Compute expiry = new Date(+validityMinutes)
  // 4. Save into storeModel.create(...)
  // 5. Return { shortLink: `${protocol}://${host}/${code}`, expiry }
  throw new Error('NotImplemented: createShortUrl');
}

/**
 * getStats(shortcode) => returns stats object or null
 *  - totalClicks, originalUrl, createdAt, expiryAt, clickEvents (array)
 */
async function getStats(shortcode) {
  // TODO: implement - read from storeModel and return structured object
  throw new Error('NotImplemented: getStats');
}

/**
 * handleRedirect(shortcode, req)
 * - Check existence and expiry
 * - Record click event: timestamp, referrer, coarse geo
 * - Increment clicks
 * - Persist if needed
 * - Return { status: 'ok', originalUrl } or { status: 'expired', expiryAt } or null
 */
async function handleRedirect(shortcode, req) {
  // TODO: implement
  throw new Error('NotImplemented: handleRedirect');
}

module.exports = {
  createShortUrl,
  getStats,
  handleRedirect
};
